### ISSUE TITLE
ipkvm fails on v1.1

### ISSUE THREAD

**Issue by ausil** [bcran/openbmc#4]
**Unexpected behavior you saw**
ipkvm fails to start
Apr 02 03:23:04 ryac-bmc systemd[1]: start-ipkvm.service: Main process exited, code=dumped, status=6/ABRT
Apr 02 03:23:04 ryac-bmc systemd[1]: start-ipkvm.service: Failed with result 'core-dump'.
Apr 02 03:23:05 ryac-bmc systemd[1]: systemd-coredump@4-1368-0.service: Deactivated successfully.
Apr 02 03:23:05 ryac-bmc systemd[1]: systemd-coredump@4-1368-0.service: Consumed 2.148s CPU time.
Apr 02 03:23:05 ryac-bmc systemd[1]: start-ipkvm.service: Scheduled restart job, restart counter is at 5.
Apr 02 03:23:06 ryac-bmc systemd[1]: Starting OpenBMC ipKVM daemon...
Apr 02 03:23:06 ryac-bmc systemd[1]: Started OpenBMC ipKVM daemon.
Apr 02 03:23:06 ryac-bmc obmc-ikvm[1672]: terminate called after throwing an instance of 'std::__ios_failure'
Apr 02 03:23:06 ryac-bmc obmc-ikvm[1672]:   what():  basic_ios::clear: iostream error
Apr 02 03:23:06 ryac-bmc systemd[1]: Started Process Core Dump (PID 1677/UID 0).

**Expected behavior**
ipkvm service to start correctly 

**To Reproduce**
1. upgrade from v1.0 to v1.1
2. 
**Screenshots**

**OpenBMC Information:**
root@ryac-bmc:~# uname -a
Linux ryac-bmc 6.6.6-83558ab-g83558ab5cb15 #1 Tue Jan  9 04:07:21 UTC 2024 armv6l GNU/Linux
root@ryac-bmc:~# cat /etc/os-release 
ID=openbmc-phosphor
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.1-bexcran"
VERSION_ID=v1.1-bexcran
VERSION_CODENAME="scarthgap"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.1-bexcran"
CPE_NAME="cpe:/o:openembedded:openbmc-phosphor:v1.1-bexcran"
BUILD_ID="20240319132120"
OPENBMC_TARGET_MACHINE="comhpcalt"
EXTENDED_VERSION="v1.1-bexcran"

**Additional context**

**Comment by bcran** [comment]
Sorry about that, an unrelated change I made to the configuration was causing it to crash.
It should be fixed in the v1.2 release I've tagged and will upload this weekend.

**Comment by bcran** [comment]
This is fixed in v1.2. If you still see a problem, please re-open this ticket.
